[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/static/*"
  to = "/dist/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200